name: Deploy React App
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci 
      - name: Test appication
        run: npm run test  
  lint: 
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci 
      - name: Lint appication
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci 
      - name: Build appication
        run: npm run build
      - name: Deploy
        run: echo Deploying...