name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci 
      - name: Test appication
        run: npm run test
      - name: Lint appication
        run: npm run lint
      - name: Build appication
        run: npm run build
      - name: Deploy
        run: echo Deploying...             